<?php

namespace ContainerDSjuuYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2waJZafService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.2waJZaf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2waJZaf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController::getAllCategories' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CategoryController::getAllCategories()', 'getCategoryControllergetAllCategoriesService', true],
            'App\\Controller\\CategoryController::getCategory' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CategoryController::getCategory()', 'getCategoryControllergetCategoryService', true],
            'App\\Controller\\CustomerController::getAllCategories' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CustomerController::getAllCategories()', 'getCustomerControllergetAllCategoriesService', true],
            'App\\Controller\\CustomerController::getCustomer' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CustomerController::getCustomer()', 'getCustomerControllergetCustomerService', true],
            'App\\Controller\\OrderController::getAllOrders' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\OrderController::getAllOrders()', 'getOrderControllergetAllOrdersService', true],
            'App\\Controller\\OrderController::getOrder' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\OrderController::getOrder()', 'getOrderControllergetOrderService', true],
            'App\\Controller\\ProductController::getAllProducts' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\ProductController::getAllProducts()', 'getProductControllergetAllProductsService', true],
            'App\\Controller\\ProductController::getProduct' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\ProductController::getProduct()', 'getProductControllergetProductService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\CategoryController:getAllCategories' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CategoryController::getAllCategories()', 'getCategoryControllergetAllCategoriesService', true],
            'App\\Controller\\CategoryController:getCategory' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CategoryController::getCategory()', 'getCategoryControllergetCategoryService', true],
            'App\\Controller\\CustomerController:getAllCategories' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CustomerController::getAllCategories()', 'getCustomerControllergetAllCategoriesService', true],
            'App\\Controller\\CustomerController:getCustomer' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\CustomerController::getCustomer()', 'getCustomerControllergetCustomerService', true],
            'App\\Controller\\OrderController:getAllOrders' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\OrderController::getAllOrders()', 'getOrderControllergetAllOrdersService', true],
            'App\\Controller\\OrderController:getOrder' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\OrderController::getOrder()', 'getOrderControllergetOrderService', true],
            'App\\Controller\\ProductController:getAllProducts' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\ProductController::getAllProducts()', 'getProductControllergetAllProductsService', true],
            'App\\Controller\\ProductController:getProduct' => ['privates', '.service_locator.IQaGfXu.App\\Controller\\ProductController::getProduct()', 'getProductControllergetProductService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategoryController::getAllCategories' => '?',
            'App\\Controller\\CategoryController::getCategory' => '?',
            'App\\Controller\\CustomerController::getAllCategories' => '?',
            'App\\Controller\\CustomerController::getCustomer' => '?',
            'App\\Controller\\OrderController::getAllOrders' => '?',
            'App\\Controller\\OrderController::getOrder' => '?',
            'App\\Controller\\ProductController::getAllProducts' => '?',
            'App\\Controller\\ProductController::getProduct' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategoryController:getAllCategories' => '?',
            'App\\Controller\\CategoryController:getCategory' => '?',
            'App\\Controller\\CustomerController:getAllCategories' => '?',
            'App\\Controller\\CustomerController:getCustomer' => '?',
            'App\\Controller\\OrderController:getAllOrders' => '?',
            'App\\Controller\\OrderController:getOrder' => '?',
            'App\\Controller\\ProductController:getAllProducts' => '?',
            'App\\Controller\\ProductController:getProduct' => '?',
        ]);
    }
}
