<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDSjuuYU\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDSjuuYU/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDSjuuYU.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDSjuuYU\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerDSjuuYU\App_KernelTestDebugContainer([
    'container.build_hash' => 'DSjuuYU',
    'container.build_id' => 'de13395c',
    'container.build_time' => 1726128024,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDSjuuYU');
